In [7]:
!pip install transformers -i https://pypi.tuna.tsinghua.edu.cn/simple
!pip install torch -i https://pypi.tuna.tsinghua.edu.cn/simple
!pip install pandas -i https://pypi.tuna.tsinghua.edu.cn/simple
!pip install scikit_learn -i https://pypi.tuna.tsinghua.edu.cn/simple

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple


In [8]:
from transformers import BertTokenizer, BertForSequenceClassification
from torch.utils.data import DataLoader
from transformers import AdamW
import pandas as pd
import os
import torch
import torch.nn as nn
from torch.nn import CrossEntropyLoss
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from tqdm import tqdm
import json
from collections import OrderedDict
from datetime import datetime
import logging
logging.basicConfig(level=logging.INFO, format='%(message)s')

In [9]:
# huggingface 分词器，wordpiece
tokenizer = BertTokenizer.from_pretrained("kykim/bert-kor-base")

In [10]:
### 读入数据
def read_data(file):
    texts = []
    labels = []
    data = pd.read_excel(file, engine='openpyxl')
    for row in data.itertuples():
        label = getattr(row, 'label')
        review = str(getattr(row, 'review'))[1:-1]
        texts.append(review)
        labels.append(label)
    assert len(texts) == len(labels)
    return texts, labels

In [11]:
texts, labels = read_data('Ko.xlsx')

In [12]:
len(texts)

30000

In [13]:
###  训练集和验证集
train_texts, val_texts, train_labels, val_labels = train_test_split(
    texts, labels, test_size=0.2, random_state=43, stratify=labels)

In [14]:
len(train_labels),len(val_labels),len(train_texts),len(val_texts)

(24000, 6000, 24000, 6000)

In [15]:
train_texts[:10]

['제 엘리트 체육은 지양할때다 저개 뭐냐??개판이',
 '번건 잘했다고 본',
 '관중 경기 아니였나요?',
 'c에서 박석민외3명에게 구상권 신청할듯네명은 거지될',
 '여자 쌍둥이 자매를 며느리삼고싶다했다는데... 에휴 그만합시다 이러다 김연경선수 갈굴까 걱정됩니',
 '포츠와 정치를 연관짓는다고 한국정치인 비판하는 일본놈들.... 양심있으면 반성하',
 '자호구 없애라. 경기 더럽게 재미없다. 몸통 펑!!하고 소리나도 점수 안오르고 진짜 뭐냐? 예전처럼 심판 몇명이서 스위치 눌러',
 '본 올림픽 부정적으로 보다만 하다가 중계는 뭔 중계냐? 대한민국의 언론수준과 이에 놀아나는 생각없는 국민들...참으로 가볍고 가볍워...ㅜ ',
 '능하면 정권을 탐하지 말아야지----- 4년 내내 상대를 까다가 ---- 올림픽 놀러가려고 대접해달면----- 니라면 하겠냐-----죽창이 뭐냐---- 조선시대냐? 공산당이냐????--- 북한넘들 지주들 죽창으로 찔러죽였던--',
 '도 방문하고 꼭 방일하기를..']

In [16]:
train_labels[:10]

[0, 1, 0, 0, 1, 0, 0, 0, 0, 1]

In [17]:
###  求最大长度，为后面分词做准备
max_len = max([len(item) for item in train_texts])
print(max_len)

max_len = max([len(item) for item in val_texts])
print(max_len)

298
298


In [18]:
### label和id进行映射
label2id = OrderedDict({item: idx for idx, item in enumerate(set(train_labels + val_labels))})
id2label = OrderedDict({v: k for k, v in label2id.items()})

In [19]:
#  训练集和验证集 分词
train_encodings = tokenizer(train_texts,
                            truncation=True,
                            padding=True,
                            max_length=128)
val_encodings = tokenizer(val_texts,
                          truncation=True,
                          padding=True,
                          max_length=128)

In [20]:
# PyTorch Dataset  创建Dataset
class CuDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        idx = int(idx)
        item = {
            key: torch.tensor(val[idx])
            for key, val in self.encodings.items()
        }
        item['labels'] = torch.tensor(label2id[self.labels[idx]])
        return item

    def __len__(self):
        return len(self.labels)

In [21]:
train_dataset = CuDataset(train_encodings, train_labels)
val_dataset = CuDataset(val_encodings, val_labels)

In [22]:
#  创建Dataloader
batch_size = 64
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
eval_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

### 加载模型

In [23]:
device = torch.device('cuda:0') if torch.cuda.is_available() else torch.device(
    'cpu')  # 使用cpu或者gpu
model = BertForSequenceClassification.from_pretrained(
    "kykim/bert-kor-base", num_labels=len(label2id))  #来加载模型，那么线性层 + 激活函数的权重就会随机初始化。我们的目的，就是通过微调，学习到线性层 + 激活函数的权重。
model.to(device)
model.train()

Some weights of the model checkpoint at kykim/bert-kor-base were not used when initializing BertForSequenceClassification: ['cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initia

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(42000, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, element

In [24]:
### 计算Accuracy，Precision，Recall，F1 score，confusion_matrix，classification_report
def compute_metrics(labels, preds):
    accuracy = accuracy_score(labels, preds)
    precision = precision_score(labels, preds)
    recall = recall_score(labels, preds)
    f1 = f1_score(labels, preds)
    print(f'accuracy: {accuracy}\n')
    print(f'precision: {precision}\n')
    print(f'recall: {recall}\n')
    print(f'f1: {f1}\n')
    print(confusion_matrix(labels, preds))
    print(classification_report(labels, preds))
    return f1

### 13.评估模型

In [25]:
@torch.no_grad()
def eval_model(model, eval_loader):
    model.eval()
    labels = []
    preds = []
    for idx, batch in enumerate(eval_loader):
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels.extend(batch['labels'].numpy())
        outputs = model(input_ids,attention_mask=attention_mask)  # 输出所有概率
        preds.extend(torch.argmax(outputs[0], dim=-1).cpu().numpy())  # 拿到标签
    f1 = compute_metrics(labels, preds)
    model.train()
    return f1

### 14.训练模型

In [26]:
optim = AdamW(model.parameters(), lr=1e-5)  # 声明优化器
step = 0
best_f1 = 0
epoch = 10
for epoch in range(epoch):
    for idx, batch in tqdm(enumerate(train_loader),
                           total=len(train_texts) // batch_size):
        optim.zero_grad()
        input_ids = batch['input_ids'].to(device)
        labels = batch['labels'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        outputs = model(input_ids=input_ids, labels=labels, attention_mask=attention_mask)
        loss = outputs[0]  # 计算Loss
        logging.info(
            f'Epoch-{epoch}, Step-{step}, Loss: {loss.cpu().detach().numpy()}')
        step += 1
        loss.backward()
        optim.step()

    print(f'Epoch {epoch}, start evaluating.')
    f1 = eval_model(model, eval_loader)  # 评估模型
    if f1 > best_f1:
        print(f'best_f1: {f1}')
        model.save_pretrained('model_best')  # 保存模型
        tokenizer.save_pretrained('model_best')
        best_f1 = f1

 26%|████████████████████▊                                                          | 99/375 [25:48<1:13:18, 15.94s/it]Epoch-0, Step-99, Loss: 0.3467811942100525


 53%|██████████████████████████████████████████▍                                     | 199/375 [51:57<45:39, 15.57s/it]Epoch-0, Step-199, Loss: 0.4218702018260956


 80%|██████████████████████████████████████████████████████████████▏               | 299/375 [1:17:41<19:50, 15.67s/it]Epoch-0, Step-299, Loss: 0.35907813906669617


100%|██████████████████████████████████████████████████████████████████████████████| 375/375 [1:37:06<00:00, 15.54s/it]


Epoch 0, start evaluating.
accuracy: 0.872

precision: 0.6913716814159292

recall: 0.5610412926391383

f1: 0.6194251734390487

[[4607  279]
 [ 489  625]]
              precision    recall  f1-score   support

           0       0.90      0.94      0.92      4886
           1       0.69      0.56      0.62      1114

    accuracy                           0.87      6000
   macro avg       0.80      0.75      0.77      6000
weighted avg       0.86      0.87      0.87      6000

best_f1: 0.6194251734390487


 26%|████████████████████▊                                                          | 99/375 [25:36<1:10:03, 15.23s/it]Epoch-1, Step-474, Loss: 0.1754956841468811


 53%|██████████████████████████████████████████▍                                     | 199/375 [51:17<45:24, 15.48s/it]Epoch-1, Step-574, Loss: 0.35499483346939087


 80%|██████████████████████████████████████████████████████████████▏               | 299/375 [1:17:44<20:10, 15.92s/it]Epoch-1, Step-674, Loss: 0.28958070278167725


100%|██████████████████████████████████████████████████████████████████████████████| 375/375 [1:37:30<00:00, 15.60s/it]


Epoch 1, start evaluating.
accuracy: 0.8735

precision: 0.6927252985884907

recall: 0.5727109515260324

f1: 0.6270270270270271

[[4603  283]
 [ 476  638]]
              precision    recall  f1-score   support

           0       0.91      0.94      0.92      4886
           1       0.69      0.57      0.63      1114

    accuracy                           0.87      6000
   macro avg       0.80      0.76      0.78      6000
weighted avg       0.87      0.87      0.87      6000

best_f1: 0.6270270270270271


 26%|████████████████████▊                                                          | 99/375 [25:20<1:10:15, 15.27s/it]Epoch-2, Step-849, Loss: 0.42874184250831604


 53%|██████████████████████████████████████████▍                                     | 199/375 [50:39<44:43, 15.25s/it]Epoch-2, Step-949, Loss: 0.24694569408893585


 80%|██████████████████████████████████████████████████████████████▏               | 299/375 [1:15:45<19:05, 15.08s/it]Epoch-2, Step-1049, Loss: 0.3222721815109253


 93%|████████████████████████████████████████████████████████████████████████▌     | 349/375 [1:28:16<06:45, 15.60s/it]Epoch-2, Step-1099, Loss: 0.2670009732246399


100%|██████████████████████████████████████████████████████████████████████████████| 375/375 [1:34:46<00:00, 15.16s/it]


Epoch 2, start evaluating.


  0%|                                                                                          | 0/375 [00:00<?, ?it/s]

accuracy: 0.8698333333333333

precision: 0.689419795221843

recall: 0.5439856373429084

f1: 0.6081284495735072

[[4613  273]
 [ 508  606]]
              precision    recall  f1-score   support

           0       0.90      0.94      0.92      4886
           1       0.69      0.54      0.61      1114

    accuracy                           0.87      6000
   macro avg       0.80      0.74      0.77      6000
weighted avg       0.86      0.87      0.86      6000



Epoch-3, Step-1125, Loss: 0.27757173776626587
 26%|████████████████████▊                                                          | 99/375 [25:59<1:27:27, 19.01s/it]Epoch-3, Step-1224, Loss: 0.1574612855911255


 40%|██████████████████████████████▉                                               | 149/375 [42:13<1:13:31, 19.52s/it]Epoch-3, Step-1274, Loss: 0.12053912878036499


 53%|██████████████████████████████████████████▍                                     | 199/375 [58:27<57:09, 19.48s/it]Epoch-3, Step-1324, Loss: 0.36801478266716003


 66%|███████████████████████████████████████████████████▊                          | 249/375 [1:14:42<41:11, 19.61s/it]Epoch-3, Step-1374, Loss: 0.2388460785150528


 80%|██████████████████████████████████████████████████████████████▏               | 299/375 [1:30:57<24:31, 19.37s/it]Epoch-3, Step-1424, Loss: 0.2328283190727234


 93%|████████████████████████████████████████████████████████████████████████▌     | 349/375 [1:47:14<08:29, 19.60s/it]Epoch-3, Step-1474, Loss: 0.22358542680740356


100%|██████████████████████████████████████████████████████████████████████████████| 375/375 [1:55:43<00:00, 18.51s/it]


Epoch 3, start evaluating.


  0%|                                                                                          | 0/375 [00:00<?, ?it/s]

accuracy: 0.8515

precision: 0.5916187345932621

recall: 0.6463195691202872

f1: 0.6177606177606177

[[4389  497]
 [ 394  720]]
              precision    recall  f1-score   support

           0       0.92      0.90      0.91      4886
           1       0.59      0.65      0.62      1114

    accuracy                           0.85      6000
   macro avg       0.75      0.77      0.76      6000
weighted avg       0.86      0.85      0.85      6000



Epoch-4, Step-1500, Loss: 0.2422596514225006
 26%|████████████████████▋                                                          | 98/375 [31:54<1:29:25, 19.37s/it]Epoch-4, Step-1598, Loss: 0.10399824380874634


 39%|██████████████████████████████▊                                               | 148/375 [47:59<1:13:52, 19.53s/it]Epoch-4, Step-1648, Loss: 0.10740702599287033


 53%|█████████████████████████████████████████▏                                    | 198/375 [1:04:09<56:29, 19.15s/it]Epoch-4, Step-1698, Loss: 0.16202138364315033


 66%|███████████████████████████████████████████████████▌                          | 248/375 [1:20:22<41:10, 19.45s/it]Epoch-4, Step-1748, Loss: 0.20881570875644684


 79%|█████████████████████████████████████████████████████████████▉                | 298/375 [1:36:30<25:14, 19.67s/it]Epoch-4, Step-1798, Loss: 0.1041577160358429


 93%|████████████████████████████████████████████████████████████████████████▍     | 348/375 [1:52:41<08:38, 19.20s/it]Epoch-4, Step-1848, Loss: 0.17817802727222443


100%|██████████████████████████████████████████████████████████████████████████████| 375/375 [2:01:27<00:00, 19.43s/it]


Epoch 4, start evaluating.


  0%|                                                                                          | 0/375 [00:00<?, ?it/s]

accuracy: 0.832

precision: 0.5378031383737518

recall: 0.6768402154398564

f1: 0.5993640699523052

[[4238  648]
 [ 360  754]]
              precision    recall  f1-score   support

           0       0.92      0.87      0.89      4886
           1       0.54      0.68      0.60      1114

    accuracy                           0.83      6000
   macro avg       0.73      0.77      0.75      6000
weighted avg       0.85      0.83      0.84      6000



Epoch-5, Step-1875, Loss: 0.1783570945262909
 26%|████████████████████▊                                                          | 99/375 [32:08<1:28:31, 19.24s/it]Epoch-5, Step-1974, Loss: 0.08095676451921463


 53%|█████████████████████████████████████████▏                                    | 198/375 [1:04:31<58:21, 19.78s/it]Epoch-5, Step-2073, Loss: 0.23597194254398346


 66%|███████████████████████████████████████████████████▌                          | 248/375 [1:20:46<41:33, 19.63s/it]Epoch-5, Step-2123, Loss: 0.15323807299137115


 93%|████████████████████████████████████████████████████████████████████████▏     | 347/375 [1:53:02<09:12, 19.74s/it]Epoch-5, Step-2222, Loss: 0.14220520853996277


100%|██████████████████████████████████████████████████████████████████████████████| 375/375 [2:02:13<00:00, 19.56s/it]


Epoch 5, start evaluating.


  0%|                                                                                          | 0/375 [00:00<?, ?it/s]

accuracy: 0.8525

precision: 0.6137040714995035

recall: 0.5547576301615799

f1: 0.5827439886845828

[[4497  389]
 [ 496  618]]
              precision    recall  f1-score   support

           0       0.90      0.92      0.91      4886
           1       0.61      0.55      0.58      1114

    accuracy                           0.85      6000
   macro avg       0.76      0.74      0.75      6000
weighted avg       0.85      0.85      0.85      6000



Epoch-6, Step-2250, Loss: 0.11234260350465775
 26%|████████████████████▋                                                          | 98/375 [29:45<1:17:19, 16.75s/it]Epoch-6, Step-2348, Loss: 0.06276065856218338


 52%|█████████████████████████████████████████▊                                      | 196/375 [55:47<48:08, 16.14s/it]Epoch-6, Step-2446, Loss: 0.12017461657524109


 78%|█████████████████████████████████████████████████████████████▏                | 294/375 [1:20:57<20:48, 15.41s/it]Epoch-6, Step-2544, Loss: 0.05608363822102547


100%|██████████████████████████████████████████████████████████████████████████████| 375/375 [1:41:59<00:00, 16.32s/it]


Epoch 6, start evaluating.


  0%|                                                                                          | 0/375 [00:00<?, ?it/s]

accuracy: 0.851

precision: 0.6141078838174274

recall: 0.5314183123877917

f1: 0.5697786333012512

[[4514  372]
 [ 522  592]]
              precision    recall  f1-score   support

           0       0.90      0.92      0.91      4886
           1       0.61      0.53      0.57      1114

    accuracy                           0.85      6000
   macro avg       0.76      0.73      0.74      6000
weighted avg       0.84      0.85      0.85      6000



Epoch-7, Step-2625, Loss: 0.06629049777984619
 26%|████████████████████▋                                                          | 98/375 [25:22<1:10:43, 15.32s/it]Epoch-7, Step-2723, Loss: 0.02777831442654133


 52%|█████████████████████████████████████████▊                                      | 196/375 [50:42<48:03, 16.11s/it]Epoch-7, Step-2821, Loss: 0.05246764048933983


 78%|█████████████████████████████████████████████████████████████▏                | 294/375 [1:17:28<21:09, 15.67s/it]Epoch-7, Step-2919, Loss: 0.056316621601581573


100%|██████████████████████████████████████████████████████████████████████████████| 375/375 [1:39:26<00:00, 15.91s/it]


Epoch 7, start evaluating.


  0%|                                                                                          | 0/375 [00:00<?, ?it/s]

accuracy: 0.8271666666666667

precision: 0.5274411974340698

recall: 0.6642728904847397

f1: 0.5880015891934843

[[4223  663]
 [ 374  740]]
              precision    recall  f1-score   support

           0       0.92      0.86      0.89      4886
           1       0.53      0.66      0.59      1114

    accuracy                           0.83      6000
   macro avg       0.72      0.76      0.74      6000
weighted avg       0.85      0.83      0.83      6000



Epoch-8, Step-3000, Loss: 0.05591762810945511
 26%|████████████████████▋                                                          | 98/375 [25:56<1:11:58, 15.59s/it]Epoch-8, Step-3098, Loss: 0.02628910169005394


 52%|█████████████████████████████████████████▊                                      | 196/375 [51:31<46:35, 15.62s/it]Epoch-8, Step-3196, Loss: 0.03535616025328636


 78%|█████████████████████████████████████████████████████████████▏                | 294/375 [1:17:38<22:07, 16.39s/it]Epoch-8, Step-3294, Loss: 0.03481097146868706


100%|██████████████████████████████████████████████████████████████████████████████| 375/375 [1:39:28<00:00, 15.92s/it]


Epoch 8, start evaluating.


  0%|                                                                                          | 0/375 [00:00<?, ?it/s]

accuracy: 0.8421666666666666

precision: 0.5727986050566696

recall: 0.5897666068222621

f1: 0.5811587793011942

[[4396  490]
 [ 457  657]]
              precision    recall  f1-score   support

           0       0.91      0.90      0.90      4886
           1       0.57      0.59      0.58      1114

    accuracy                           0.84      6000
   macro avg       0.74      0.74      0.74      6000
weighted avg       0.84      0.84      0.84      6000



Epoch-9, Step-3375, Loss: 0.06399337947368622
 26%|████████████████████▋                                                          | 98/375 [26:56<1:16:25, 16.55s/it]Epoch-9, Step-3473, Loss: 0.01864663138985634


 52%|█████████████████████████████████████████▊                                      | 196/375 [53:30<46:22, 15.54s/it]Epoch-9, Step-3571, Loss: 0.048235874623060226


 78%|█████████████████████████████████████████████████████████████▏                | 294/375 [1:18:56<20:51, 15.45s/it]Epoch-9, Step-3669, Loss: 0.023858746513724327


100%|██████████████████████████████████████████████████████████████████████████████| 375/375 [1:39:59<00:00, 16.00s/it]


Epoch 9, start evaluating.
accuracy: 0.8475

precision: 0.5893980233602875

recall: 0.5888689407540395

f1: 0.5891333632689717

[[4429  457]
 [ 458  656]]
              precision    recall  f1-score   support

           0       0.91      0.91      0.91      4886
           1       0.59      0.59      0.59      1114

    accuracy                           0.85      6000
   macro avg       0.75      0.75      0.75      6000
weighted avg       0.85      0.85      0.85      6000



In [27]:
def predict(model, tokenizer, text):
    encoding = tokenizer(text,
                         return_tensors="pt",
                         max_length=128,
                         truncation=True,
                         padding=True)
    encoding = {k:v.to(device) for  k,v in encoding.items()}
    outputs = model(**encoding)
    #pred = id2label[torch.argmax(outputs[0], dim=-1).numpy()[0]]
    pred = id2label[torch.argmax(outputs[0], dim=-1).cpu().detach().numpy()[0]]
    return pred

In [28]:
tokenizer = BertTokenizer.from_pretrained("model_best")
model = BertForSequenceClassification.from_pretrained(
    "model_best", num_labels=len(label2id))
model.to(device)    

In [ ]:
import numpy as np
result_dict = {}
for root, dirs, files in os.walk('test', topdown=True):
    for name in files:
        all_preds = []
        print(f'process file: {name}')
        try:
            with open(os.path.join(root, name), 'r', encoding='utf8') as f:
                lines = f.readlines()
        except:
            with open(os.path.join(root, name), 'r', encoding='gb18030') as f:
                lines = f.readlines()
        for idx, line in enumerate(lines):
            line = line.strip()
            if not line:
                continue
            text = line
            pred=predict(model,tokenizer,line)
            all_preds.append(pred)
        base_name_date = '-'.join([os.path.basename(name)[4:6], os.path.basename(name)[6:8]])
        result_dict[datetime.strptime(base_name_date, "%m-%d")] = [round(
            sum(all_preds) / len(all_preds), 2), len(all_preds)]
result_dict = sorted(result_dict.items(), key=lambda x: x[0])
np.save('result_dict_Ko.npy', result_dict)

process file: 20210623.csv
process file: 20210624.csv
process file: 20210625.csv
process file: 20210626.csv
process file: 20210627.csv
process file: 20210628.csv
process file: 20210629.csv
process file: 20210630.csv
process file: 20210701.csv
process file: 20210702.csv
process file: 20210703.csv
process file: 20210704.csv
process file: 20210705.csv
process file: 20210706.csv
process file: 20210707.csv
process file: 20210708.csv
process file: 20210709.csv
process file: 20210710.csv
process file: 20210711.csv
process file: 20210712.csv
process file: 20210713.csv
process file: 20210714.csv
process file: 20210715.csv
